### ISSUE TITLE
TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by misode** [SPGoding/datapack-language-server#375]
I got this error randomly when typing. A new error appeared every time I entered or removed a character. Saving the file fixed the error. Have not been able to reproduce.

```
(node:18036) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'slice' of undefined
    at Object.t.default (c:\Users\Misode\.vscode\extensions\spgoding.datapack-language-server-1.13.8\dist\server.js:1:1739218)
    at c:\Users\Misode\.vscode\extensions\spgoding.datapack-language-server-1.13.8\dist\server.js:1:207092
(node:18036) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'slice' of undefined
    at Object.t.default (c:\Users\Misode\.vscode\extensions\spgoding.datapack-language-server-1.13.8\dist\server.js:1:1739218)
    at c:\Users\Misode\.vscode\extensions\spgoding.datapack-language-server-1.13.8\dist\server.js:1:207092
(node:18036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:18036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 3:52:32 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'length' of undefined
  Code: -32603 
```

**Comment by SPGoding** [comment]
Thank you! The error stack really helps.

The error was thrown while handling incremental updating. However I have no idea why it happened because the string that `slice` was called on should never be `undefined` 🤔

**Comment by misode** [comment]
This just happened again.
```
TypeError: Cannot read property 'slice' of undefined
    at Object.t.default (c:\Users\Misode\.vscode\extensions\spgoding.datapack-language-server-2.0.0\dist\server.js:1:2626156)
    at c:\Users\Misode\.vscode\extensions\spgoding.datapack-language-server-2.0.0\dist\server.js:1:300986
info.strings = execute as @s run scoreboard players add #manager temp 1
execute if score #manager temp matches 1 run datapack disable "file/DirectEntityTest"
execute if score #manager temp matches 1 run tellraw @s [{"text":"Dropcompressing ","bold":true},{"text":"disabled","color":"red","bold":true},{"text":".","color":"black","bold":true}]
execute if score #manager temp matches 2.. run scoreboard players set #manager temp 0
execute if score #manager temp matches 0 run datapack enable "file/DirectEntityTest"
execute if score #manager temp matches 0 run tellraw @s [{"text":"Dropcompressing ","bold":true},{"text":"enabled","color":"green","bold":true},{"text":".","color":"black","bold":true}]
execute as @s run scoreboard players set @s temp 0

* * * * * *
range = {"start":{"line":9,"character":4},"end":{"line":9,"character":4}}
```
