### ISSUE TITLE
20w46a item modifiers are not supported

### ISSUE THREAD

**Issue by SirWindfield** [SPGoding/datapack-language-server#762]
When creating a new item modifier json file under `namespace:item_modifiers`, I get the following output:
```
Tried to access schema "item_modifier", but that doesn't exist.
[Error - 9:26:54 PM] Request textDocument/colorPresentation failed.
  Message: Request textDocument/documentColor failed with message: Cannot read property 'default' of undefined
  Code: -32603 
(node:10860) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'default' of undefined
    at new t.DataModel (c:\Users\me\.vscode\extensions\spgoding.datapack-language-server-3.1.1\dist\server.js:1:1082620)
    at Function.setUp (c:\Users\me\.vscode\extensions\spgoding.datapack-language-server-3.1.1\dist\server.js:1:319124)
    at Function.validate (c:\Users\me\.vscode\extensions\spgoding.datapack-language-server-3.1.1\dist\server.js:1:317594)
    at Object.t.parseJsonNode (c:\Users\me\.vscode\extensions\spgoding.datapack-language-server-3.1.1\dist\server.js:1:72030)
    at P.parseJsonDocument (c:\Users\me\.vscode\extensions\spgoding.datapack-language-server-3.1.1\dist\server.js:1:348361)
    at P.<anonymous> (c:\Users\me\.vscode\extensions\spgoding.datapack-language-server-3.1.1\dist\server.js:1:347955)
    at Generator.next (<anonymous>)
    at s (c:\Users\me\.vscode\extensions\spgoding.datapack-language-server-3.1.1\dist\server.js:1:342005)
(node:10860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 716)
[Error - 9:26:54 PM] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: Cannot read property 'default' of undefined
  Code: -32603 
[Error - 9:26:54 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'default' of undefined
  Code: -32603 
[Error - 9:26:54 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'default' of undefined
  Code: -32603 
```

**Comment by SPGoding** [comment]
Select `1.17` for `datapack.env.jsonVersion` in Settings.

**Comment by SirWindfield** [comment]
I missed that, sorry!
